### ISSUE TITLE
[CI] Patterns: Generate JSON Schema and Definitions for KUMA components

### ISSUE THREAD

**Issue by sayantan1413** [meshery/meshery-kuma#174]
**Enhancement Description**

To generate the workflow of getting the manifest from the KUMA using the [kubeopenapi-jsonschema](https://github.com/layer5io/kubeopenapi-jsonschema) to read and generate json schemas from those manifests and then also generating workload definitions from those schemas.

A sample workflow is [here](https://github.com/DelusionalOptimist/meshery-istio/blob/gen-oam/.github/workflows/update-oam-defs.yml)

---

**Comment by Shreyas220** [comment]
hey @sayantan1413, is this up for grabs?

**Comment by leecalcote** [comment]
@Shreyas220, go, go, go. 🙂

**Comment by Shreyas220** [comment]
@leecalcote i am gonna take my time with this one :sweat_smile:

**Comment by leecalcote** [comment]
High quality: gooood 🙂
Long time to deliver: not so gooood 😕

if you’re not quite sure how to approach this, please raise up questions quickly.
