### ISSUE TITLE
[CI] Update Slack.yml and add newcomer-alert workflow

### ISSUE THREAD

**Issue by cpepper96** [meshery/meshery-kuma#219]
**Current Behavior**
Currently the slack.yml is outdated. Also there is no automated way of notifying the slack channel when a "good first issue" has been created.

**Desired Behavior**
Update slack.yml and add newcomer-alert.yml to the Github workflow. 

---
**Resources**
Add the updated slack.yml file and the newcomer-alert.yml file to the .github/workflow folder.

Files needed:
https://github.com/meshery/meshery-istio/blob/master/.github/workflows/slack.yml
https://github.com/layer5io/layer5/blob/master/.github/workflows/newcomers-alert.yml

**Comment by Ankita13-code** [comment]
Hi @cpepper96 @leecalcote @warunicorn19! I would like to take up this issue. Can you please assign it to me?

**Comment by sayantan1413** [comment]
🚀

**Comment by Ankita13-code** [comment]
I have opened a PR for this issue. Please take a look @sayantan1413

**Comment by theBeginner86** [comment]
Hi @msaini0r,
As you have raised a couple of PRs regarding the updation of slack and newcomers-alert workflows. So, would you mind updating the slack.yml workflow for this issue as-well? 

> We already have a [PR](https://github.com/meshery/meshery-kuma/pull/227) for updating newcomers-alert.yml workflow.

**Comment by msaini0r** [comment]
@theBeginner86 sure. I will do it in few minutes.

**Comment by theBeginner86** [comment]
Thank you, @msaini0r 😊

**Comment by msaini0r** [comment]
@theBeginner86 Please review this pr.
