### ISSUE TITLE
[Docs]The updation of shields is needed in README.md 

### ISSUE THREAD

**Issue by Swapnil-Bhabal** [meshery/meshery-kuma#222]
**Current State:**
Small updation of shields in README.md

![image](https://user-images.githubusercontent.com/61308713/146510352-3a6d17aa-d57c-44a2-b0d5-8df0c8c74745.png)

**Desired State:**
This is how it should look like

![image](https://user-images.githubusercontent.com/61308713/146510403-c898843d-e8aa-4df3-82ed-dea1dd67dd2b.png)

updation should be done in this README.md by keeping the shield style uniform to following meshery-istio's README.md :
https://github.com/meshery/meshery-istio/blob/721b78783182e65145cefde64d905dab3ca20ba1/README.md?plain=1#L13

---
**Contributor Resources**
- [Meshery documentation site](https://docs.meshery.io/)
- [Meshery documentation source](https://github.com/meshery/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

**Comment by leecalcote** [comment]
psst. @Swapnil-Bhabal.... @msaini0r has a grammatical learning to pass along.
