### ISSUE TITLE
Invalid e2e workflow 

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery-kuma#228]
**Description**
See - https://github.com/meshery/meshery-kuma/actions/runs/1616010189

```
Invalid workflow file : .github/workflows/e2etest.yaml#L37
The workflow is not valid. .github/workflows/e2etest.yaml (Line: 37, Col: 11): Input k8s_version is required, but not provided while calling. .github/workflows/e2etest.yaml (Line: 37, Col: 11): Input sm_version is required, but not provided while calling.
```

### Contributor Resources

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- See the [Contributing to Meshery.io Website](https://github.com/layer5io/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- See Meshery site designs in this [Figma designfile](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI?node-id=110%3A1). Fill-in the [Layer5 Community Member Form](https://layer5.io/newcomer) and join the [Layer5 Community Slack](http://slack.layer5.io) for access.

**Comment by leecalcote** [comment]
@alphaX86, @Revolyssup ...

**Comment by Revolyssup** [comment]
> @alphaX86, @Revolyssup ...

I know this issue. It will be fixed tomorrow
