### ISSUE TITLE
Add end-to-end tests using service-mesh-pattern file.

### ISSUE THREAD

**Issue by Zanda256** [meshery/meshery-kuma#259]
#### Current Behavior
Currently e2e tests in the adapter only run tests for vanilla service mesh installation and for addons.

#### Desired Behavior
The link below is of an example patternfile that should also be deployed and assertions should be made.
https://github.com/service-mesh-patterns/service-mesh-patterns/blob/master/samples/minimalistiobookinfo.yaml

#### Reference:

- [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)

**Comment by leecalcote** [comment]
@Zanda256 are you chasing this one down?

**Comment by Zanda256** [comment]
I will first finish the meshkit issue, tonight. Then choose what else I can take on.
