### ISSUE TITLE
[Readme] Consistently present Meshery logo

### ISSUE THREAD

**Issue by legendarykamal** [meshery/meshery-kuma#324]
Current Situation
A brief description of what the current circumstance is.

As you see the current logo is quite big and is not consistent.
Desired Situation
A brief description of the necessary action to take.

Make it consistent with github.com/meshery/meshery 's readme lo
---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 📝 [Meshery Adapters Spreadsheet](https://docs.google.com/spreadsheets/d/1rGGpSXC68iDJzNRU-qZIRQsZUwkt1qLFg7JCs4pfvbU/edit?usp=sharing)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by pratul20** [comment]
Hi @legendarykamal can I work on this issue?

**Comment by Abhishek-kumar09** [comment]
@legendarykamal Would you like to give some info to the contributors to adress what is the current/desired behaviour with some example?

**Comment by Abhishek-kumar09** [comment]
So I just noticed it is meshery/kuma, so the Kuma logo is quite big in size. There needs a request to make it smaller, 32 px might be a good one.

**Comment by legendarykamal** [comment]
@Abhishek-kumar09 i had already mentioned it in the description but thanks for elaborating more.

**Comment by UtkarshMishra12** [comment]
@legendarykamal  I would like to work on this issue. Can you please assign it to me?

**Comment by pratul20** [comment]
@UtkarshMishra12  I am already working on this issue
