### ISSUE TITLE
[CI] Create new workflow for updating file `meshmodel_metadata.json`

### ISSUE THREAD

**Issue by ayushthe1** [meshery/meshery-kuma#366]
#### Current Behavior

Currently,we have to manually update the values for keys like "logourl,svg_color,etc." in the json file.
#### Desired Behavior

A workflow which takes these values from the [integration spreadsheet](https://docs.google.com/spreadsheets/d/1DZHnzxYWOlJ69Oguz4LkRVTFM79kC2tuvdwizOJmeMw/edit#gid=0) and updates the json file.
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 📝 [Meshery Adapters Spreadsheet](https://docs.google.com/spreadsheets/d/1rGGpSXC68iDJzNRU-qZIRQsZUwkt1qLFg7JCs4pfvbU/edit?usp=sharing)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by shruti1421** [comment]
Hello, @ayushthe1. I'd want to work on this issue; could you help explain how to do so, as I'm new to contributing to this project?

**Comment by ayushthe1** [comment]
Hey @shruti1421 ,Thanks for taking interest in this issue. However, I'm already working on this issue so please take look at some other issues preferably in the meshery repo (as a lot of issues are open there).

**Comment by yash37158** [comment]
is this issue fixed @ayushthe1?

**Comment by ayushthe1** [comment]
@yash37158 sorry, I missed your previous message .I haven't created this workflow yet and I won't be able to work on it for the next 2 weeks as I'll be busy with other stuff. 
You can take up on this issue if you want

**Comment by yash37158** [comment]
Thanks for your words @ayushthe1, you can assign this to me

**Comment by yash37158** [comment]
Hey, @Revolyssup @leecalcote do I need to create a new workflow file?

**Comment by ayushthe1** [comment]
yes @yash37158 ,you would need to create a new workflow for this.

**Comment by yash37158** [comment]
Thanks @ayushthe1 for clarifying. Will create a PR asap

**Comment by yash37158** [comment]
Hey @ayushthe1, can you please ping ashish's workflow ?

**Comment by 8rxn** [comment]
Hey @ayushthe1, If the issue is still relevant, I would like to work on this issue?

**Comment by leecalcote** [comment]
Thanks for inquiring, folks. I don't know that @ayushthe1 was able to keep pace with the status of the work here, however, this issue has been implemented already and can be closed.

@8rxn, while this particular item has been implemented, there are other, upcoming needs in this area. Here's a link to the [current implementation](https://github.com/meshery/meshery/tree/master/scripts/component_updation). 

In terms of next steps, let's finish up our chat in Slack and get a couple new issues opened up.

**Comment by leecalcote** [comment]
Oh, wait. I thought this issue was opened on meshery/meshery, but I see that it is in meshery/meshery-kuma. I'm reopening and will let @ayushthe1 speak to its status.

**Comment by leecalcote** [comment]
@Revolyssup  can you offer direction here?

**Comment by leecalcote** [comment]
@Revolyssup could you tie this off?

**Comment by yashchaddha** [comment]
Hi @leecalcote would like to work on this one

**Comment by leecalcote** [comment]
Thanks for this, @yashchaddha. @ayushthe1 will you give @yashchaddha an overview of the spreadsheet and the issue to be solved here?
