### ISSUE TITLE
NewIssueWelcomeComment In Github Workflow has a dead link

### ISSUE THREAD

**Issue by yashchaddha** [meshery/meshery-kuma#403]
**Description**
A brief description of the issue.
Thanks for opening this issue. A contributor will be by to give feedback soon. In the meantime, please review the [Layer5 Contributors' Welcome Guide](https://docs.google.com/document/d/17OPtDE_rdnPQxmk2Kauhm3GwXF1R5dZ3Cj8qZLKdo5E/edit?usp=sharing), engage in the [discussion forum](https://discuss.layer5.io/), and be sure to join the [community Slack](http://slack.layer5.io/).

https://docs.google.com/document/d/17OPtDE_rdnPQxmk2Kauhm3GwXF1R5dZ3Cj8qZLKdo5E/edit?usp=sharing

This link when accessed, turns out to be a dead link

<img width="383" alt="image" src="https://github.com/meshery/meshery-kuma/assets/25150314/f23cc75a-90f4-4b97-bb50-1f61cd1ecd89">

**Expected Behavior**
A brief description of what you expected to happen.

Should be an active link

- Link to be provided by the maintainers.

**Screenshots**
Add screenshots, if applicable, to help explain your problem.

**Enviroment:**
 - OS: [e.g. Ubuntu]
 - Browser: [e.g. Chrome, Safari]
 - Version: [e.g. 22]
 - Device: [e.g. laptop, iPhone 8]

---
[Optional] **To Reproduce**

[Optional] **Additional Context**

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 📝 [Meshery Adapters Spreadsheet](https://docs.google.com/spreadsheets/d/1rGGpSXC68iDJzNRU-qZIRQsZUwkt1qLFg7JCs4pfvbU/edit?usp=sharing)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by yashchaddha** [comment]
Hi @leecalcote I would like to contribute on this.

Also, could you please provide me the active link which needs to be pasted

**Comment by leecalcote** [comment]
Super, super. Thank you, @yashchaddha

**Comment by yashchaddha** [comment]
Hi @leecalcote can I please get the right link which needed to be pasted?

Thanks

**Comment by leecalcote** [comment]
@Chadha93

**Comment by Chadha93** [comment]
@yashchaddha Newcomer's link you can add - https://layer5.io/community/newcomers. Could you also clean up the issue description and title?

**Comment by yashchaddha** [comment]
@Chadha93  Sure I would.

Thankyou for the link.
