### ISSUE TITLE
[CI] Kuma adapter tests failing

### ISSUE THREAD

**Issue by sandramsc** [meshery/meshery-kuma#430]
#### Current Behavior

Currently the [Kuma adapter](https://github.com/meshery/meshery-kuma/actions/runs/7966793759/job/21748614314#step:25:10) tests are failing
#### Desired Behavior

The tests should be able to pass at all stages, resulting in a successfully implemented workflow.

#### Implementation

The Meshery Kuma adapter Dockerfile needs an image update, Alpine… with glibc..
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 📝 [Meshery Adapters Spreadsheet](https://docs.google.com/spreadsheets/d/1rGGpSXC68iDJzNRU-qZIRQsZUwkt1qLFg7JCs4pfvbU/edit?usp=sharing)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by sandramsc** [comment]
Not resolved

**Comment by devhindo** [comment]
I recently opened a pr that could solve this issue
I can't confirm as the logs of the action you mentioned is expired
